# Generated by Django 5.2.3 on 2025-07-21 22:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_parkingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='device_id',
            field=models.UUIDField(default=uuid.UUID('00000000-0000-0000-0000-000000000000')),
        ),
        migrations.AddIndex(
            model_name='parkingsession',
            index=models.Index(fields=['device_id', 'parking_lot'], name='core_parkin_device__bdc9bb_idx'),
        ),
    ]
