# Generated by Django 5.2.3 on 2025-07-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_parkingsession_device_id_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='parkingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('end_time__isnull', True)), fields=('device_id',), name='unique_active_parking_session_per_device'),
        ),
    ]
