# Generated by Django 5.2.3 on 2025-07-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_parkingsession_unique_active_parking_session_per_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglot',
            name='reserved_slots',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
