# Generated by Django 5.2.3 on 2025-07-27 18:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_parkinglot_reserved_slots'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('room', 'Room'), ('hallway', 'Hallway'), ('stairs', 'Stairs'), ('elevator', 'Elevator')], max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_nodes', to='core.floor')),
            ],
        ),
        migrations.CreateModel(
            name='PathEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(help_text='Distance in meters')),
                ('end_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='core.pathnode')),
                ('start_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='core.pathnode')),
            ],
        ),
    ]
