# Generated by Django 5.2.3 on 2025-07-27 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pathnode_pathedge'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathnode',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='path_node', to='core.room'),
        ),
    ]
