# Generated by Django 5.2.3 on 2025-07-28 08:34

from django.db import migrations

def create_pathnodes_for_rooms(apps, schema_editor):
    Room = apps.get_model('core', 'Room')
    PathNode = apps.get_model('core', 'PathNode')

    for room in Room.objects.all():
        PathNode.objects.create(
            floor=room.floor,
            node_type='room',
            geom=room.geom
        )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pathnode_room'),  
    ]

    operations = [
        migrations.RunPython(create_pathnodes_for_rooms),
    ]
