# Generated by Django 5.2.3 on 2025-07-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_create_pathnodes_for_existing_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='used_reserved_slot',
            field=models.BooleanField(default=False),
        ),
    ]
