# Generated by Django 5.2.3 on 2025-07-30 15:22

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_parkingsession_used_reserved_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Main Entrance', 'North Door'", max_length=100)),
                ('entry_type', models.CharField(choices=[('main', 'Main Entrance'), ('side', 'Side Entrance'), ('back', 'Back Entrance'), ('emergency', 'Emergency Exit'), ('service', 'Service Entrance'), ('accessible', 'Accessible Entrance')], default='main', max_length=20)),
                ('geom', django.contrib.gis.db.models.fields.PointField(help_text='Precise coordinates of the entry point', srid=4326)),
                ('is_main', models.BooleanField(default=False, help_text='Is this the main entrance?')),
                ('is_accessible', models.BooleanField(default=True, help_text='Is this entrance wheelchair accessible?')),
                ('is_24_7', models.BooleanField(default=True, help_text='Is this entrance available 24/7?')),
                ('opening_hours', models.CharField(blank=True, help_text="e.g., '08:00-17:00' if not 24/7", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Additional details about this entrance')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_points', to='core.building')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('building',), name='unique_main_entrance_per_building')],
            },
        ),
    ]
